-- MySQL Script generated by MySQL Workbench
-- Fri 15 Jun 2018 02:03:58 PM SAST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Team` (
  `idTeam` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `numberOfMember` INT NOT NULL,
  PRIMARY KEY (`idTeam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player` (
  `idPlayer` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `score` INT NOT NULL,
  `gamePlayed` BIGINT NOT NULL,
  `totalLeaguePoints` BIGINT NOT NULL,
  `Team_idTeam` INT NOT NULL,
  PRIMARY KEY (`idPlayer`),
  INDEX `fk_Player_Team1_idx` (`Team_idTeam` ASC),
  CONSTRAINT `fk_Player_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Game` (
  `idGame` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `gamePlayed` INT NOT NULL,
  `gameWon` VARCHAR(45) NOT NULL,
  `Player_idPlayer` INT NOT NULL,
  PRIMARY KEY (`idGame`),
  INDEX `fk_Game_Player1_idx` (`Player_idPlayer` ASC),
  CONSTRAINT `fk_Game_Player1`
    FOREIGN KEY (`Player_idPlayer`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GameInstance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GameInstance` (
  `idGameInstance` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `timer` DATE NULL,
  `player1` VARCHAR(45) NULL,
  `player2` VARCHAR(45) NULL,
  `Player_idPlayer` INT NOT NULL,
  PRIMARY KEY (`idGameInstance`),
  INDEX `fk_GameInstance_Player1_idx` (`Player_idPlayer` ASC),
  CONSTRAINT `fk_GameInstance_Player1`
    FOREIGN KEY (`Player_idPlayer`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Leader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Leader` (
  `idLeader` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `score` INT NOT NULL,
  `gamePlayed` INT NOT NULL,
  `gameWon` INT NOT NULL,
  `Team_idTeam` INT NOT NULL,
  `GameInstance_idGameInstance` INT NOT NULL,
  PRIMARY KEY (`idLeader`, `Team_idTeam`, `GameInstance_idGameInstance`),
  INDEX `fk_Leader_Team_idx` (`Team_idTeam` ASC),
  INDEX `fk_Leader_GameInstance1_idx` (`GameInstance_idGameInstance` ASC),
  CONSTRAINT `fk_Leader_Team`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Leader_GameInstance1`
    FOREIGN KEY (`GameInstance_idGameInstance`)
    REFERENCES `mydb`.`GameInstance` (`idGameInstance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
